# Generated by Django 4.1.2 on 2022-11-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_product_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
